[project]
name = "irods-client-system-tray"
version = "0.1.0"
authors = [
  { name="iRODS Consortium", email="info@irods.org" },
]
description = "iRODS Ingest from the System Tray"
requires-python = ">=3.10"
readme = "README.md"
license = "BSD-3-Clause"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "pyside6>=6.7",
    "pytest>=8.0",
    "pytest-cov>=7.0",
    "pyobjc-framework-Cocoa>=10.0 ; sys_platform == 'darwin'",
    "python-irodsclient>=3.0",
    "send2trash>=1.8",
    "watchdog>=4.0",
    "win11toast>=0.36 ; sys_platform == 'win32'",
]

[project.scripts]
irods-client-system-tray = "irods_client_system_tray.main:main"

[project.urls]
Repository = "https://github.com/irods/irods_client_system_tray"
Issues = "https://github.com/irods/irods_client_system_tray/issues"

[build-system]
requires = [
   "setuptools >= 40.9.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[tool.setuptools.packages.find]
include = ["irods_client_system_tray*"]
exclude = ["tests*", "venv*"]

[tool.setuptools.package-data]
irods_client_system_tray = ["irods_logo.svg", "theme.qss.template"]
